services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations/up:/docker-entrypoint-initdb.d
  api:
    build: .
    depends_on:
      - postgres
    environment:
      HOST: "localhost"
      PORT: "8080"
      LOG_LEVEL: "INFO"
      DATABASE: "postgres"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/shortener?sslmode=disable"
      CLIENT_URL: "http://localhost:3000"
    ports:
      - 8080:8080
    profiles:
      - release
volumes:
  postgres_data:
